from schemas import AlertSeverity

INTERACTIONS = [
    {"name":"amoxicillin","aliases":["amoxil"],"category":"Antibiotic (Penicillin)","effect_on_inr":"Increase","magnitude":"Mild (+0.3–0.6)","mechanism":"Gut flora reduction → ↓ Vitamin K2 synthesis","clinical_action":"Monitor INR 5–7 days after starting. Consider reducing warfarin 10–15%.","severity":AlertSeverity.warning},
    {"name":"ciprofloxacin","aliases":["cipro"],"category":"Antibiotic (Fluoroquinolone)","effect_on_inr":"Increase","magnitude":"Moderate (+0.6–1.2)","mechanism":"CYP1A2 inhibition + gut flora reduction","clinical_action":"Check INR 3–5 days after starting. Reduce warfarin by 15–25%.","severity":AlertSeverity.warning},
    {"name":"metronidazole","aliases":["flagyl"],"category":"Antibiotic/Antiprotozoal","effect_on_inr":"Increase","magnitude":"Strong (+1.0–2.0)","mechanism":"Potent CYP2C9 inhibitor","clinical_action":"Reduce warfarin 25–50%. Check INR within 3 days. HIGH RISK.","severity":AlertSeverity.critical},
    {"name":"trimethoprim-sulfamethoxazole","aliases":["bactrim","septra","tmp-smx"],"category":"Antibiotic (Sulfonamide)","effect_on_inr":"Increase","magnitude":"Strong (+0.6–1.5)","mechanism":"CYP2C9 inhibition + gut flora reduction","clinical_action":"Reduce warfarin 25%. Check INR within 5 days.","severity":AlertSeverity.critical},
    {"name":"fluconazole","aliases":["diflucan"],"category":"Antifungal (Azole)","effect_on_inr":"Increase","magnitude":"Strong (+1.5–3.0)","mechanism":"Potent CYP2C9 & CYP3A4 inhibitor","clinical_action":"Reduce warfarin 30–50%. Check INR in 2–3 days. CRITICAL.","severity":AlertSeverity.critical},
    {"name":"itraconazole","aliases":["sporanox"],"category":"Antifungal (Azole)","effect_on_inr":"Increase","magnitude":"Moderate-Strong (+1.0–2.0)","mechanism":"CYP3A4 inhibition","clinical_action":"Reduce warfarin 20–40%. Monitor INR closely.","severity":AlertSeverity.critical},
    {"name":"amiodarone","aliases":["cordarone","pacerone"],"category":"Antiarrhythmic","effect_on_inr":"Increase","magnitude":"Moderate-Strong (+0.8–1.5)","mechanism":"CYP2C9 & CYP3A4 inhibitor; half-life 40–55 days","clinical_action":"Reduce warfarin 30–50%. Monitor weekly for months. Effect persists after stopping.","severity":AlertSeverity.critical},
    {"name":"ibuprofen","aliases":["advil","motrin","nurofen"],"category":"NSAID","effect_on_inr":"Increase + Bleeding Risk","magnitude":"Mild INR (+0.2–0.5) but significant GI bleeding risk","mechanism":"COX-1 inhibition impairs platelet aggregation","clinical_action":"Avoid if possible. If needed, use minimum dose. Consider PPI.","severity":AlertSeverity.warning},
    {"name":"naproxen","aliases":["aleve","naprosyn"],"category":"NSAID","effect_on_inr":"Increase + Bleeding Risk","magnitude":"Mild (+0.2–0.4); significant bleeding risk","mechanism":"COX-1 inhibition; longer half-life than ibuprofen","clinical_action":"Avoid. Paracetamol is safer for pain in anticoagulated patients.","severity":AlertSeverity.warning},
    {"name":"omeprazole","aliases":["prilosec","losec"],"category":"PPI","effect_on_inr":"Increase","magnitude":"Mild (+0.1–0.3)","mechanism":"Weak CYP2C19 inhibition","clinical_action":"Low risk. Routine monitoring sufficient.","severity":AlertSeverity.info},
    {"name":"simvastatin","aliases":["zocor"],"category":"Statin","effect_on_inr":"Increase","magnitude":"Mild (+0.1–0.25)","mechanism":"Mild CYP3A4 competition","clinical_action":"Monitor INR when starting or changing dose.","severity":AlertSeverity.info},
    {"name":"rifampin","aliases":["rifampicin","rifadin"],"category":"Antibiotic (Rifamycin)","effect_on_inr":"Decrease","magnitude":"Strong (−1.0 to −2.5)","mechanism":"Potent CYP2C9 & CYP3A4 inducer","clinical_action":"May need to DOUBLE warfarin. Monitor every 3–5 days. Watch for INR rebound after stopping.","severity":AlertSeverity.critical},
    {"name":"carbamazepine","aliases":["tegretol"],"category":"Anticonvulsant","effect_on_inr":"Decrease","magnitude":"Moderate-Strong (−1.0–1.5)","mechanism":"CYP enzyme induction","clinical_action":"Increase warfarin significantly. Monitor INR closely during titration.","severity":AlertSeverity.critical},
    {"name":"aspirin","aliases":["asa","acetylsalicylic acid"],"category":"Antiplatelet","effect_on_inr":"Mild Inc + Bleeding Risk","magnitude":"Low INR effect; synergistic bleeding risk","mechanism":"Irreversible COX-1 inhibition","clinical_action":"Low-dose (81 mg) may be acceptable per guidelines for mechanical valves. Avoid higher doses.","severity":AlertSeverity.warning},
    {"name":"levothyroxine","aliases":["synthroid","thyroxine"],"category":"Thyroid Hormone","effect_on_inr":"Increase","magnitude":"Variable (+0.3–1.0)","mechanism":"Increases catabolism of clotting factors","clinical_action":"Adjust warfarin when thyroid status or levothyroxine dose changes.","severity":AlertSeverity.warning},
    {"name":"spinach","aliases":["baby spinach"],"category":"High Vitamin K Food","effect_on_inr":"Decrease","magnitude":"High — 494 mcg VitK/100g","mechanism":"Dietary VitK directly counteracts warfarin","clinical_action":"Maintain consistent weekly intake. Sudden increases will lower INR.","severity":AlertSeverity.warning},
    {"name":"kale","aliases":["curly kale","cavolo nero"],"category":"Very High Vitamin K Food","effect_on_inr":"Decrease","magnitude":"Very High — 817 mcg VitK/100g","mechanism":"Extremely high VitK content","clinical_action":"Limit to consistent small amounts. Do not start eating large quantities without INR check.","severity":AlertSeverity.critical},
    {"name":"cranberry juice","aliases":["cranberry","cranberry extract"],"category":"CYP Inhibitor Food","effect_on_inr":"Increase","magnitude":"Moderate (+0.5–1.5)","mechanism":"CYP2C9 inhibition despite low VitK","clinical_action":"Avoid large quantities. Check INR if patient begins regular consumption.","severity":AlertSeverity.warning},
    {"name":"grapefruit","aliases":["grapefruit juice","pomelo"],"category":"CYP Inhibitor Food","effect_on_inr":"Increase","magnitude":"Mild-Moderate","mechanism":"CYP3A4 inhibition via furanocoumarins","clinical_action":"Limit to occasional use. Monitor INR if consumed regularly.","severity":AlertSeverity.info},
    {"name":"alcohol","aliases":["beer","wine","spirits","ethanol"],"category":"Alcohol","effect_on_inr":"Increase (acute) / Variable (chronic)","magnitude":"Moderate-High with heavy use","mechanism":"Acute heavy intake inhibits CYP2C9; chronic heavy use induces CYP enzymes","clinical_action":"Advise consistent moderate intake (<=14 units/week). Warn about binge drinking risks.","severity":AlertSeverity.warning},
    {"name":"garlic supplement","aliases":["garlic extract","allicin"],"category":"Herbal Supplement","effect_on_inr":"Increase","magnitude":"Mild","mechanism":"Antiplatelet effect via thromboxane inhibition","clinical_action":"Dietary garlic is safe. Avoid high-dose supplements.","severity":AlertSeverity.info},
    {"name":"st. john's wort","aliases":["hypericum","stjohn wort","st johns wort"],"category":"Herbal Supplement","effect_on_inr":"Decrease","magnitude":"Strong (−0.5–2.0)","mechanism":"Potent CYP3A4 and P-glycoprotein inducer","clinical_action":"CONTRAINDICATED with warfarin. Discontinue immediately. Monitor INR closely.","severity":AlertSeverity.critical},
    {"name":"fish oil","aliases":["omega-3","omega 3","epa dha"],"category":"Supplement","effect_on_inr":"Increase","magnitude":"Mild at low doses; moderate at >3g/day","mechanism":"Inhibits platelet aggregation","clinical_action":"Doses <=1g/day generally safe. Monitor if patient takes high-dose supplements.","severity":AlertSeverity.info},
    {"name":"broccoli","aliases":["broccolini"],"category":"Moderate Vitamin K Food","effect_on_inr":"Decrease","magnitude":"Moderate — 141 mcg VitK/100g","mechanism":"Dietary VitK counteracts warfarin","clinical_action":"Maintain consistent intake. Large sudden increases can lower INR.","severity":AlertSeverity.info},
]

def search_interactions(query):
    q=query.lower().strip()
    results=[e for e in INTERACTIONS if q in e["name"].lower() or any(q in a.lower() for a in e.get("aliases",[]))]
    if not results:
        results=[e for e in INTERACTIONS if e["name"].lower().startswith(q[:4]) or any(a.lower().startswith(q[:4]) for a in e.get("aliases",[]))]
    return results
